### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [milespossing/Azure-Keyvault-Zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by milespossing** [comment]
Hey @unixorn, thank you so much for the consideration. I've added the license file in #2.
